language: python
python:
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"
 - "pypy"
 - "pypy3"
install:
 - "pip install boto requests cloudpickle futures doctest-ignore-unicode"
 - if [[ $TRAVIS_PYTHON_VERSION != 'pypy'* ]]; then pip install pylzma; fi
 - "pip install ."
script: "nosetests -vv"
